# this file is the single source of truth for all model-specific configurations.
# the `scripts/process-predictions.py` script uses this to determine adapters, paths, and parameters.

# keys are the canonical model names used in directory structures and CLI commands.
models:
  aizynthfinder-mcts:
    adapter: aizynth
    raw_results_filename: results.json.gz
  aizynthfinder-retro-star:
    adapter: aizynth
    raw_results_filename: results.json.gz
  askcos:
    adapter: askcos
    raw_results_filename: results.json.gz
  retrochimera:
    adapter: retrochimera
    raw_results_filename: results.json.gz
  dream-retroer:
    adapter: dreamretro
    raw_results_filename: results.json.gz
  retro-star:
    adapter: retrostar
    raw_results_filename: results.json.gz
  retro-star-n1-n5-stock:
    adapter: retrostar
    raw_results_filename: results.json.gz
  retro-star-buyables-stock:
    adapter: retrostar
    raw_results_filename: results.json.gz
  multistep-ttl:
    adapter: multistepttl
    raw_results_filename: results.json.gz
  dms-flash-fp16:
    adapter: dms
    raw_results_filename: valid_results.json.gz
  dms-wide-fp16:
    adapter: dms
    raw_results_filename: valid_results.json.gz
  dms-explorer-XL-fp16:
    adapter: dms
    raw_results_filename: valid_results.json.gz
  synplanner-mcts:
    adapter: synplanner
    raw_results_filename: results.json.gz
  synplanner-eval:
    adapter: synplanner
    raw_results_filename: results.json.gz
  syntheseus-bfs-local-retro:
    adapter: syntheseus
    raw_results_filename: results.json.gz
  syntheseus-retro0-local-retro:
    adapter: syntheseus
    raw_results_filename: results.json.gz
  synllama:
    adapter: synllama
    raw_results_filename: results.json.gz
